name: netflix
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.3
  firebase_core: ^1.19.1
  video_player: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/netflix.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Netflix Sans
      fonts:
        - asset: fonts/NetflixSans-Regular.otf
        - asset: fonts/NetflixSans-Light.otf
          weight: 300
        - asset: fonts/NetflixSans-Medium.otf
          weight: 500
        - asset: fonts/NetflixSans-Bold.otf
          weight: 700

