// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdzIn-VLjGVlYF5f3mEn7FDZJ0ls6xyKs',
    appId: '1:787423297158:web:1dda4feffbb34142269b07',
    messagingSenderId: '787423297158',
    projectId: 'netflix-3b950',
    authDomain: 'netflix-3b950.firebaseapp.com',
    storageBucket: 'netflix-3b950.appspot.com',
    measurementId: 'G-MKS5TYVEDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVX7yRHLMEO3BayRQnYS-txIlZiObQAoQ',
    appId: '1:787423297158:android:7a6422d523bba3d7269b07',
    messagingSenderId: '787423297158',
    projectId: 'netflix-3b950',
    storageBucket: 'netflix-3b950.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Rcbptm5VHTV164oYJSJvuTcsGMAhiII',
    appId: '1:787423297158:ios:932043a0949c116b269b07',
    messagingSenderId: '787423297158',
    projectId: 'netflix-3b950',
    storageBucket: 'netflix-3b950.appspot.com',
    iosClientId: '787423297158-b5nuuejnpcm54jiof97255jq746rj8vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Rcbptm5VHTV164oYJSJvuTcsGMAhiII',
    appId: '1:787423297158:ios:932043a0949c116b269b07',
    messagingSenderId: '787423297158',
    projectId: 'netflix-3b950',
    storageBucket: 'netflix-3b950.appspot.com',
    iosClientId: '787423297158-b5nuuejnpcm54jiof97255jq746rj8vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflix',
  );
}
